server:
  port: 8400

spring:
  application:
    name: ONLINE-TEST-APM-Spring-Admin
  security:
    user:
      name: otp
      password: 123456
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  thymeleaf:
    cache: false